### ISSUE TITLE
JSON::ParserError: A JSON text must at least contain two octets!

### ISSUE THREAD

**Issue by scott** [jtkendall/ruser#3]
Just started seeing this error anywhere a RUser call is made.  Trace:

```
Loading development environment (Rails 4.2.7.1)
2.2.1 :001 > RUser.new
JSON::ParserError: A JSON text must at least contain two octets!
    from /Users/scott/.rvm/gems/ruby-2.2.1/gems/json-1.8.3/lib/json/common.rb:155:in `initialize'
    from /Users/scott/.rvm/gems/ruby-2.2.1/gems/json-1.8.3/lib/json/common.rb:155:in `new'
    from /Users/scott/.rvm/gems/ruby-2.2.1/gems/json-1.8.3/lib/json/common.rb:155:in `parse'
    from /Users/scott/.rvm/gems/ruby-2.2.1/gems/ruser-3.0.0/lib/ruser.rb:37:in `new'
    from (irb):1
    from /Users/scott/.rvm/gems/ruby-2.2.1/gems/railties-4.2.7.1/lib/rails/commands/console.rb:110:in `start'
    from /Users/scott/.rvm/gems/ruby-2.2.1/gems/railties-4.2.7.1/lib/rails/commands/console.rb:9:in `start'
    from /Users/scott/.rvm/gems/ruby-2.2.1/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:68:in `console'
    from /Users/scott/.rvm/gems/ruby-2.2.1/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
    from /Users/scott/.rvm/gems/ruby-2.2.1/gems/railties-4.2.7.1/lib/rails/commands.rb:17:in `<top (required)>'
    from bin/rails:4:in `require'
    from bin/rails:4:in `<main>'
```

**Comment by jtkendall** [comment]
Hi Scott, sorry about that it looks like RandomUser.me changed to using secure urls and I hadn't noticed it. The new version (3.0.1) of RUser should now (or very soon) be available via updating the gem
